### ISSUE TITLE
iptb-plugins fails

### ISSUE THREAD

**Issue by LastExile16** [ipfs/iptb#106]
I have opened the issue in iptb-plugins but it seems no one looks at it. I thought I may get an answer here:
installing iptb-plugins with`make install` results in this error:
../../../../gx/ipfs/QmbK4EmM2Xx5fmbqK38TGP3PpY66r3tkXLZTcc7dF9mFwM/go-ipfs-config/serialize/serialize.go:13:2: cannot find package "github.com/facebookgo/atomicfile" in any of: /usr/local/go/src/github.com/facebookgo/atomicfile (from $GOROOT) /home/nawras/go/src/github.com/facebookgo/atomicfile (from $GOPATH) Makefile:33: recipe for target 'install' failed make: *** [install] Error 1
I have checked the `atomicfile` repository, it says it is archived.
any fixes?

**Comment by LastExile16** [comment]
I have downloaded `atomicfile` manually and changed its parent directory name from `facebookgoarchive` to `facebookgo`, the packages problem solved but still installation failed showing:

```
$ make install
gx-go rw
(cd iptb; go install)
# github.com/ipfs/iptb-plugins/iptb
./iptb.go:18:3: cannot use pluginlocalipfs.NewNode (type func(string, map[string]string) ("gx/ipfs/QmckeQ2zrYLAXoSHYTGn5BDdb22BqbUoHEHm8KZ9YWRxd1/iptb/testbed/interfaces".Core, error)) as type "github.com/ipfs/iptb/testbed/interfaces".NewNodeFunc in field value
./iptb.go:31:3: cannot use plugindockeripfs.NewNode (type func(string, map[string]string) ("gx/ipfs/QmckeQ2zrYLAXoSHYTGn5BDdb22BqbUoHEHm8KZ9YWRxd1/iptb/testbed/interfaces".Core, error)) as type "github.com/ipfs/iptb/testbed/interfaces".NewNodeFunc in field value
./iptb.go:44:3: cannot use pluginbrowseripfs.NewNode (type func(string, map[string]string) ("gx/ipfs/QmckeQ2zrYLAXoSHYTGn5BDdb22BqbUoHEHm8KZ9YWRxd1/iptb/testbed/interfaces".Core, error)) as type "github.com/ipfs/iptb/testbed/interfaces".NewNodeFunc in field value
Makefile:33: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by travisperson** [comment]
Sorry for the delay, lets carry on this discussion over at the `iptb-plugins` repo on your original issue.

https://github.com/ipfs/iptb-plugins/issues/4
