### ISSUE TITLE
How to set and find the Bootstrap nodes?

### ISSUE THREAD

**Issue by LastExile16** [ipfs/iptb#115]
I couldn't find anything about setting bootstrap nodes, but looking into some issues I found examples using `--bootstrap` flag. but the flag is unrecognized when I use it.

```
$ iptb init [0-4] --bootstrap=none
Incorrect Usage: flag provided but not defined: -bootstrap

NAME:
   iptb init - initialize specified nodes (or all)

USAGE:
   iptb init [nodes] -- [arguments...]

CATEGORY:
   CORE
flag provided but not defined: -bootstrap
```

**Comment by Stebalien** [comment]
The IPTB interface was completely refactored to make it more general purpose (i.e., work with more than *just* IPFS). That flag is probably gone.

To add a bootstrap node, you'll have to run `iptb run -- ipfs bootstrap add ...` after initializing. That'll add the requested bootstrap node to all test nodes.

**Comment by LastExile16** [comment]
Thank you so much.
