### ISSUE TITLE
How to start docker node

### ISSUE THREAD

**Issue by lry666-yep** [ipfs/iptb#130]
I installed Docker
![image](https://user-images.githubusercontent.com/62842768/103989906-5d45d280-51cb-11eb-9c29-a8ae68fba2a7.png)
and I'm using the following command
![image](https://user-images.githubusercontent.com/62842768/103990110-a85fe580-51cb-11eb-8269-5a1ff57179ba.png)
I started the IPFS Docker node, but the Docker container ended automatically after 20 seconds.... I don't know why
Also, I get an error when I try to set the delay as follows
![image](https://user-images.githubusercontent.com/62842768/104005348-f0890300-51df-11eb-8287-96fd5e36581c.png)
Looking forward to your reply
thanks！

**Comment by jessicaschilling** [comment]
Hi @lry666-yep -- this is actually a better question for the forums at https://discuss.ipfs.io. Can you please post there? Closing this issue - thanks!
