### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by chriscool** [ipfs/iptb#5]
Right now I get:

```
> go install
main.go:19:2: cannot find package "github.com/alecthomas/kingpin" in any of:
        /usr/local/go/src/github.com/alecthomas/kingpin (from $GOROOT)
        /home/utilisateur/gocode/src/github.com/alecthomas/kingpin (from $GOPATH)
```

It works after `go get github.com/alecthomas/kingpin`, but maybe it would be better if it used gx (or something else) to manage the dependency, as we might want to use iptb in go-ipfs, fs-repo-migrations and maybe other repos.

**Comment by whyrusleeping** [comment]
you can run: `go get` in the directory to fetch any deps it might have. iptb is currently using the standard `go get` installation method. I'll switch to gx for it soon
