### ISSUE TITLE
UTP Nodes

### ISSUE THREAD

**Issue by davinci26** [ipfs/iptb#64]
Hey,

I saw on the code that there is support for UTP, but when I try to spawn UTP nodes I get an error. The steps to reproduce are:

    ./iptb init -n 5 -f -utp
    ./iptb start

Then I get the following error: 
```node {Node PK} failed to come online in given time period```

I was able to reproduce this error both in Mac OSX and Linux Ubuntu 16.04. I also tried to use dockernodes instead of local nodes but I get the same error.

Is this a deprecated feature or am I doing something wrong?

**Comment by Stebalien** [comment]
Yes. UTP support was removed.
