### ISSUE TITLE
Allow connecting *all* nodes or a cluster of nodes fully

### ISSUE THREAD

**Issue by Stebalien** [ipfs/iptb#68]
See: https://github.com/ipfs/iptb/pull/61#discussion_r208416445

**Comment by travisperson** [comment]
This snuck into #61 at the end

`iptb connect` will connect every node to every other node, like running `iptb connect [0-N] [0-N]` where `N` is the last index of the nodes.

It also supports `iptb connect [j-k]`, which is treated like `iptb connect [j-k] [j-k]`.
