### ISSUE TITLE
IPTB Plugins - MacOS (Darwin)

### ISSUE THREAD

**Issue by davinci26** [ipfs/iptb#70]
I was trying to run the IPTB framework and encountered issues with the load plugin function in `spec.go`. 

OS: MacOS High Sierra v10.13.4
Go: go1.10.3 darwin/amd64

Issue: I can compile the program successfully and the plugins using
```
1. make
2. make plugins
3. make install_plugins
```

Then I run the following command:
`./iptb auto -count 3 -type localipfs` and get the following stacktrace:

```
/Users/davinci/testbed/plugins/dockeripfs.so
runtime: bad pointer in frame main.loadPlugins at 0xc420127ab8: 0x1d
fatal error: invalid pointer found on stack

runtime stack:
...
```
For readability purposes, I created a pastebin link with the full [stack trace (view here)](https://pastebin.com/SiuSUJ0t)

Note 1: I added a `print line` to make sure that the directory is pointing correctly (See the first line of stacktrace).

Note 2: The load-plugins function has another issue as well: if an OS hidden file is created in the plugins directory then the code breaks. This happened to me because MacOS creates a directory file if you open a directory with Finder, [(.DS_Store)](https://en.wikipedia.org/wiki/.DS_Store). Then IPTB tried also to open the .DS_Store file as a plugin.

Note 3: I used the same procedure to compile it under Ubuntu 16 LTS and it runs successfully.

Note 4: Similar issues on Golang Github repository [Go Issue #23369](https://github.com/golang/go/issues/23369)

P.S. I will try to solve the problem cause I want to run IPTB it in my laptop and let you know if I have any useful findings

**Comment by travisperson** [comment]
Go 1.11 was just released which should fix the plugin loading issue. Can you give it a try and see if it resolves the issue for you?

**Comment by davinci26** [comment]
Indeed Go 1.11 fixed, maybe this could be added in the Readme file under the installation tab
