### ISSUE TITLE
Pass options to docker exec/RunCmd

### ISSUE THREAD

**Issue by dgrisham** [ipfs/iptb#83]
It would be nice to be able to pass options directly to the underlying `RunCmd` for a node -- for example, in the `dockeripfs` case, we would support passing options directly to `docker exec`. This is impossible at the moment because [all args to `docker exec` are inserted after the docker ID argument](https://github.com/ipfs/iptb/blob/7ec7d1d1a01a718a118547e0ae8ad75a563475f9/plugins/ipfs/docker/dockeripfs.go#L231).

My initial thought is that we would extend `RunCmd` to accept additional arguments called e.g. and `opts` list that the user can add to using flags called `--shortopts` and `--longopts`. For example, if we wanted to pass `--detach` to a `dockeripfs` node so that the `docker exec` runs in the background:

```
iptb run --shortopts d 0 -- echo "This is running in a detached container."
iptb run --longopts detach 0 -- echo "This is running in a detached container."
```

(In the case of `localipfs`, we just prepend the `opts` to the `args` list in `RunCmd` since the issue doesn't exist there.)

Then we just prepend `-` and `--` as necessary.

I personally like the idea of these being passed to all commands that are under a single `iptb run`, e.g.

```
iptb run --longopts detach <<CMD
0 -- echo "Running on 0 and detaching."
1 -- echo "Running on 1 and detaching."
CMD
```

Multiple long options could be passed as:

```
iptb run --longopts detach,privileged
```

And, of course, for short options:

```
iptb run --shortopts dp
```

Thoughts? Maybe there's a nicer way than `--shortopts` and `--longopts` that I'm not seeing, but that doesn't seem so bad to me.

**Comment by dgrisham** [comment]
Whoops, the proposed `--shortopts` doesn't support args. Maybe:

```
iptb run --shortopts 'a0,b1,c false'
```

**Comment by travisperson** [comment]
> support passing options directly to docker exec

I'm not sure we want to support this. It starts to leak a bit more than I think we want to about what might be behind the plugin on the core interface.

It would probably be better to grab the container id from the plugin and execute the docker command directly.

I don't think this value is exposed currently, but it should be pretty simple to add it. The docker plugin has a `getID` method already, so it should just take adding a few lines to expose it as an attribute.

**Comment by dgrisham** [comment]
Gotcha, yeah after thinking a bit more about it I realized that 1. it doesn't really generalize any particular behavior very well (the arguments you pass to `docker exec` wouldn't be the same as the arguments you pass to some other backend), and 2. it introduces kind of an awkward syntax for something that can be done pretty straightforwardly otherwise.

I like the `getID` method idea, I actually wanted that recently but ended up going with `docker exec $(cat $IPTB_ROOT/testbeds/default/$i/dockerid)` isntead, which is subpar. I'll make a PR with the `getID` addition.
