### ISSUE TITLE
Running `iptb connect` too quickly after `iptb start`

### ISSUE THREAD

**Issue by dgrisham** [ipfs/iptb#86]
When scripting IPTB commands, I occasionally come across the following:

```
$ iptb start --wait
$ iptb connect
node[0] => node[1]: could not find valid swarm address for peer QmSzgKjAYCJw
node[1] => node[0]: could not find valid swarm address for peer QmPQLzRx32FB 
```

This is because the IPFS nodes vary in how quickly they are able to get a public swarm address. To fix this, I've simply changed `iptb connect` to `until iptb connect; do :; done`. That's simple enough, but I figured I'd see if we wanted to add a way for either

1. `iptb start --wait` to also wait until the node(s) have a public swarm address (or have another option to do so), or
2. `iptb connect` to try a few times before failing on this specific error.

Users can also check for a public addr with something like `iptb run <node> -- ipfs id | grep ip4 | grep -v 127`, so it's not impossible to get the info, but being able to run `iptb start` and `iptb connect` in sequence without having to account for this subtlety might be reasonable. This is a fairly small detail, but thought I'd see if we want to address this or leave it be.

**Comment by travisperson** [comment]
Option 1 would be my preferred route initially, but I'm not sure if we can always assume that a node will have addresses. Ultimately it's up to the plugin, so we could make this decision. However, that might limit the plugin, or at least the `--wait` option when using it.

Option 2 is probably a safer bet.

**Comment by travisperson** [comment]
Actually, while the above might also be good to have, it turns out that the docker plugin does not respect `wait`. We need these lines in the docker plugin.

https://github.com/ipfs/iptb/blob/319a620c0328148f437d07cb7ee0477d8cf2e4ce/plugins/ipfs/local/localipfs.go#L186-L188

**Comment by travisperson** [comment]
> So, go-ipfs should start listening on the swarm addresses before it starts the API. Is that not the case?

I have no reason to doubt this, good to know. The issues is within the docker iptb plugin. It currently does not handle the wait flag and returned immediately without checking if the API is online.

Given the above, we just need to add the check.

**Comment by Stebalien** [comment]
Got it (but please doubt it, we tend to have quite a few startup race conditions).

**Comment by dgrisham** [comment]
Thanks for the info @Stebalien, we can add an additional check if any issues arise but for now let's assume https://github.com/ipfs/iptb/pull/89 fixes this.
